services:

  order-pgadmin:
    container_name: order-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@orderapp.com
      PGADMIN_DEFAULT_PASSWORD: 123456

    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    
    ports: 
     - "5050:80"
